elm-jp/guide

book/types/README.md

Translation types/README

---

book/types/reading_types.md

translate types/reading_types

---

book/types/type_aliases.md

Translate types/type_aliases

---

book/appendix/types_as_sets.md

Translate appendix/types_as_sets

---

book/README.md

README.md の翻訳（つづき）

---

.circleci/config.yml

CircleCIを利用して、masterの変更を検知して自動でdocsをビルドし直す機構を作成。
- 翻訳のアップデートだけでなく、いかなるmasterの変更に対しても反応します
- 手元で作業している人はmasterのrebase回数が多くなるかもしれません
- コミット権限のある人がGithubの`Personal access tokens`機能を使って、`Full control of private repositories`権限を持ったトークンを発行する必要があります
- さらに、そのトークンは`GITHUB_ACCESS_TOKEN`という名前の環境変数としてCircleCIに登録する必要があります
- 登録されたトークンは自分ですら末尾4桁しか表示されないのでセキュリティ的には安全です

翻訳アップデート時の自動ビルド

---

book/appendix/function_types.md

translate appendix/function_types

---

book/webapps/navigation.md

Translate webapps/navigation

---

book/webapps/url_parsing.md

This PR closes #48  (対応するissue番号に変えてください)

Translate webapps/url_parsing

---

book/optimization/README.md

Translate optimization/readme

---

.travis.yml
script/diff_evancz_guide.sh

こんな感じのメッセージがくるはず
```
Spidey BotBOT今日 午後5時20分
以下のファイルで原文の更新がありました。
book/README.md 
book/appendix/function_types.md 
book/architecture/buttons.md 
book/effects/README.md 
book/effects/http.md 
book/effects/json.md 
book/interop/ports.md 
book/next_steps.md 
book/optimization/keyed.md 
book/webapps/README.md 
book/webapps/url_parsing.md 
redirects.json 
https://travis-ci.org/elm-jp/guide/builds/432361453
```
問題は、取り込むまで無限に通知してくる（うざそう）

原文が更新されてたら Discord に通知

---

book/about_translation.md
book/effects/README.md

ちゃんとできてるが不安ですが…
This PR closes #33

translate effects/README

---

book/optimization/lazy.md

Translate optimization/lazy

---

book/optimization/keyed.md

Translate optimization/keyed

---

book/about_translation.md
book/architecture/README.md

https://github.com/elm-jp/guide/pull/88
これのcommit履歴をきれいにしたやつ。
よく考えたら aratama さんがフォークしたリポジトリへの書き込み権がなかったので新しいPRにしちゃいます。
僕がけっこうゴリゴリ対訳表をいじるPRをmasterにマージしてしまってご不便おかけします m(_ _)m
This PR closes #20
This PR also closes #88

Translate architecture/readme

---

book/interop/README.md

This PR closes #39 (対応するissue番号に変えてください)
WIPを外しました！レビューお願いします

translate interop/README.md

---

book/appendix/types_as_bits.md

Translate appendix/types_as_bits

---

book/types/pattern_matching.md

* 日本語訳が浸透している用語はカタカナ語にしない
* 日本語訳よりもカタカナ語が十分に浸透していてグーグラビリティなども高い場合は無理に日本語訳をせずにカタカナ表記にする
* カタカナ語としても日本語としてもあまり浸透しておらず、パッと見で意味が分かる日本語訳もない場合はカタカナ語を推奨する
This PR is part of #106

pattern matchingのtodoと全体を確認

---

book/types/reading_types.md

* 日本語訳が浸透している用語はカタカナ語にしない
* 日本語訳よりもカタカナ語が十分に浸透していてグーグラビリティなども高い場合は無理に日本語訳をせずにカタカナ表記にする
* カタカナ語としても日本語としてもあまり浸透しておらず、パッと見で意味が分かる日本語訳もない場合はカタカナ語を推奨する
This PR is part of #106

reading typesのtodoを訳して、全体を手直しした

---

book/architecture/buttons.md

以下のツイートを見て
「え？ 別に抽象化は最高ではないよね？ 本当に最高だったら特定の型にしか使えないような関数を書くよりも動的型付けにしてあらゆる型に対してあらゆる関数を適用できるようにしたほうが抽象的で最高になるのに、Elmはそうしていないよね？」
って思ったので、原文のニュアンスに寄せてみました！
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">elmのhello worldであるボタンのページが新しく翻訳されました！<br>初心者がハマりがちなviewが最初書きづらいところの理由やelmのパフォーマンスってどうなの？ 抽象化サイコー！って話が書いてあります！<a href="https://t.co/3W8taWr1bz">https://t.co/3W8taWr1bz</a></p>&mdash; ABAB↑↓BA (@ababupdownba) <a href="https://twitter.com/ababupdownba/status/1088576487085596672?ref_src=twsrc%5Etfw">January 24, 2019</a></blockquote>

抽象化は別に最高じゃない

---

book/appendix/types_as_sets.md
book/error_handling/README.md
book/interop/ports.md
book/optimization/lazy.md

This PR merges changes on original content (English version).

Keep up changes on original content

---

book/install.md

book/install.md の更新し忘れを修正

---

book/effects/json.md

Merge changes on original content

---

book/about_translation.md
build.sh

Merge changes on original version

---

book/install.md

Translate new TODOs

---

book/effects/http.md

更新していまます → 更新しています

---

book/about_translation.md
book/architecture/forms.md
book/architecture/text_fields.md
repl/build.sh
repl/elm.json
repl/src/Repl.elm

原文に追従（2019/10/30時点の最新4109eaeまで）

---

book/SUMMARY.md

Translate 'SUMMARY'

---

book/README.md

最後のTODOは特に、あまり自信がありませんが、レビューをお願いします。
This PR closes #174

october-dev「はじめに」の翻訳

---

book/next_steps.md

「次への一歩」のリンクを最新化する

---

book/SUMMARY.md
book/about_translation.md
book/types/custom_types.md
book/types/type_aliases.md

type alias の訳を「型エイリアス」に変更

---

book/install/README.md

インストールの翻訳(october-dev)

---

book/install/elm.md

This PR closes #187
以下の箇所はちょっと自信がありません…。
```
Line:129
```
```
Line:141
This is the most general way to compile Elm code. It is extremely useful once your project becomes too advanced for `elm reactor`.
`elm make`はElmのコードをコンパイルする最も一般的な方法です。`elm reactor`では不十分なほどプロジェクトが複雑になってしまった場合にとても役に立ちます。
```

インストール/Elmの翻訳

---

book/error_handling/maybe.md

This PR closes #222  (対応するissue番号に変えてください)

error_handling/maybe.mdの翻訳

---

book/core_language.md

This PR closes #204 
時間かかってしまってすみません…！
最後から数えて2つ目の文「したがって、年齢を更新する関数は次のようになると思います。」はちょっと自信ナシです…

translate core_language

---

book/types/reading_types.md

This PR closes #233  (対応するissue番号に変えてください)

Update reading types

---

book/effects/json.md

非常にささいなつづりの修正だけです。ガイドの内容そのものには影響ありません🙂

JSONのつづりを修正

---

book/about_translation.md
book/error_handling/maybe.md

原文に追従（Maybeのellieのコンパイルエラー解消）

---

.gitignore
.npmrc
package-lock.json
package.json
repl/.npmrc
repl/package-lock.json

* node のバージョンを指定するハックをいれた
* アプリケーションは`package-lock.json`をgitリポジトリーに含めたほうが適切なのでそうなるように`.npmrc`を削除

ビルド時の依存バージョンをできるだけあわせる

---

book/types/reading_types.md

非常に些細な修正ですが、negate関数のドキュメントへのリンクが正常に機能していなかったので修正しました。

negateへのリンクを貼る

---

book/about_translation.md
book/core_language.md
book/error_handling/README.md
book/error_handling/maybe.md
book/interop/README.md
book/interop/flags.md
book/optimization/asset_size.md
repl/templates/wrapper.txt

- ほとんどが本家guideに入ったtypo等の修正で、日本語訳には影響ありません。
- 唯一日本語訳に影響するのが`error_handling/README.md `です。レビューしていただけると幸いです。
- asset_size.md の最後は余計に引用（>）が入っていたため1つ削除しました。

February merge

---

book/effects/json.md

ねぎぼうずさんが教えてくれた本家の変更を取り込みました🎉
まずevan-apr-5ブランチに本家の変更を取り込み、変更が大きい部分をTODOにしておきました。
こちらのPRはそのTODOを翻訳したものです。
マージされたらevan-apr-5をmasterブランチにマージ予定です 🖋🍍🍎🖋

新しい変更箇所の対応

---

book/types/custom_types.md
package-lock.json

訳注としてカスタム型の補足記事にリンクを貼りました。
---
This PR closes #248

カスタム型についての補足説明記事にリンクを貼る
